### ISSUE TITLE
[Bug] Bullet list items (2-n) improperly indented until begin typing

### ISSUE THREAD

**Issue by apg-dev** [MarkEdit-app/MarkEdit#672]
Not sure if this bug was recently introduced or if I never noticed it before. But creating a bullet list by typing a `-` or `*` is behaving strangely on subsequent lines after the first.

Steps to reproduce:
- Create a list like this one by typing `-` or `*` and entering text
- Hit Return and all subsequent bullets will be indented a few spaces ... until you start typing, whereupon the bullet "outdents" back to the expected location.

**Comment by apg-dev** [comment]
Well that got me thinking, and I wrongly assumed that the only thing that had changed was downloading the latest codebase. But then I realized I also lifted your sample css:

```css
.cm-line {
  margin: 0 auto !important;
  max-width: 800px !important;
}
```

And that is the culprit. If I remove that block, then we get "normal" bullets.

**Comment by apg-dev** [comment]
That fixes it!! Thank you for the fast response!

**Comment by apg-dev** [comment]
I should have noticed the `cm-line` given the other css right below it. Sorry about that.

CSS-related, here's what I'm doing for a code snippet background. Not sure if this is best solution. Ideally I'd love to target and hide the triple backticks and language unless cursor is within the code block, but I'm not sure how easy that is within CodeMirror.

```css
.cm-md-codeBlock {
  background-color: rgba(246, 245, 245, 0.6); 
}

@media (prefers-color-scheme: dark) {
  .cm-md-codeBlock {
    background-color: rgba(30, 30, 30, 0.8); 
    color: rgba(255, 255, 255, 0.9); 
  }
}
```
